### ISSUE TITLE
Cannot Open database

### ISSUE THREAD

**Issue by Ioanniy** [FrankHausmann/IOSKeePass#14]
After Update to todays new Version 2.00, the program can Not Open kdbx file. Error: password incorrect.

nach heutigem Update auf version 2.00, kann ich die Dantenbank nicht mehr öffnen. 
Fehler: Passwörter stimmen nicht überein.
Mit keePassium funktioniert alles!
![846881F4-9FD3-496D-9C3B-08685BA7A243](https://user-images.githubusercontent.com/82656925/115023715-71325c00-9ebf-11eb-84d5-88bd002625d2.png)

**Comment by FrankHausmann** [comment]
First of all, thank you for your comment.
Since IOSKeePass is used 55% in the US, it is important that we agree on the English language here, even if this is sometimes difficult for German (I am myself). 
On the subject of version 2.0.0 not being released yet, but only being made available for external testing, please excuse me. I have now removed IOS Keepass from the AppStore again, because especially with DBs that have more than 16 rounds in Argon2 hashing 3it comes to performance problems on the iPhone.


I don't know when I will release it again, as it is a hobby project.

**Comment by seltner** [comment]
Tested new Version 2.0 with new created database
with keepass - v2.47
Database file encrypt algoritm: AES/Rijndael (256-bit key, FIPS 197)
Key derivation function: AES-KDF
Iterations: 60000
Compression: GZip

database could be opened - and also be modified (added new group)
save, close, reopen -> no errors detected

**Comment by seltner** [comment]
so i have created 6 new testdatabases with [keepass  V2.47](https://keepass.info/) with different settings - password only - 
all databases could be opened and modified by the IOSKeePass App

here my testsettings:

Database file encrypt algoritm | Key derivation function | Other |
------------ | ------------- | -------------
AES/Rijndael (256-bit key, FIPS 197) | AES-KDF | Iterations: 60000 + Compression: GZip|
AES/Rijndael (256-bit key, FIPS 197) | Argon-2d  | Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip|
AES/Rijndael (256-bit key, FIPS 197) | Argon-2id | Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip|
ChaCha20 (256-bit key, RFC 7539) | AES-KDF | Iterations: 60000 + Compression: GZip|
ChaCha20 (256-bit key, RFC 7539) | Argon-2d  | Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip|
ChaCha20 (256-bit key, RFC 7539) | Argon-2id | Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip|

could you provide more informations about your database? do you use password and also a keyfile ?

**Comment by Ioanniy** [comment]
Hallo Frank,
I use the database with keyfile.
I think that this is the reason for the Problem i have.
Thank you for the Information an the Good job.
Please contact me when the app is downloadable again.

Ich finde es einfach sicherer mit Schlüsseldatei und Passwort die Datei zu verschlüsseln.
Für Ihre Mühe vielen Dank.

Mit freundlichen Grüßen 

Ioannis Coucoumaftsis
Bodelschwinghstr. 2
92224 Amberg

Am 23.04.2021 um 08:33 schrieb Stefan Eltner ***@***.***>:

﻿
so i have created 6 new testdatabases with keepass V2.47 with different settings - password only -
all databases could be opened and modified by the IOSKeePass App

here my testsettings:

Database file encrypt algoritm	Key derivation function	Other
AES/Rijndael (256-bit key, FIPS 197)	AES-KDF	Iterations: 60000 + Compression: GZip
AES/Rijndael (256-bit key, FIPS 197)	Argon-2d	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
AES/Rijndael (256-bit key, FIPS 197)	Argon-2id	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
ChaCha20 (256-bit key, RFC 7539)	AES-KDF	Iterations: 60000 + Compression: GZip
ChaCha20 (256-bit key, RFC 7539)	Argon-2d	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
ChaCha20 (256-bit key, RFC 7539)	Argon-2id	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
could you provide more informations about your database? do you use password and also a keyfile ?

**Comment by FrankHausmann** [comment]
Hi 
thanks Ioannis, thanks Stefan for the Testing.

A new Release 2.0.1 is the App-Store Connect but in the moment on Reviewing by Apple.
The hard crashes from Verison 2.0.0 is fixed, and small feature are including (Bug fixes while Moving, Infos about dbs and yubikit preparations).

At the moment i fight with Yubikit for the HMAC SHA1 challenge response NFC alone is no way to many restrictions and
only IOS 14.4 will be supported for NFC, so that only the lightning port are practicable, unfortunately i don`t have one at the moment.
 
ASAP i have time i will look deeper to clarify whats going wrong with the keyfiles

**Comment by Ioanniy** [comment]
New Version download.
Works Fine! 👍


Ioannis Coucoumaftsis
Bodelschwinghstr. 2
92224 Amberg

Am 23.04.2021 um 08:42 schrieb Ioannis Coucoumaftsis ***@***.***>:

﻿Hallo Frank,
I use the database with keyfile.
I think that this is the reason for the Problem i have.
Thank you for the Information an the Good job.
Please contact me when the app is downloadable again.

Ich finde es einfach sicherer mit Schlüsseldatei und Passwort die Datei zu verschlüsseln.
Für Ihre Mühe vielen Dank.

Mit freundlichen Grüßen 

Ioannis Coucoumaftsis
Bodelschwinghstr. 2
92224 Amberg

Am 23.04.2021 um 08:33 schrieb Stefan Eltner ***@***.***>:

﻿
so i have created 6 new testdatabases with keepass V2.47 with different settings - password only -
all databases could be opened and modified by the IOSKeePass App

here my testsettings:

Database file encrypt algoritm	Key derivation function	Other
AES/Rijndael (256-bit key, FIPS 197)	AES-KDF	Iterations: 60000 + Compression: GZip
AES/Rijndael (256-bit key, FIPS 197)	Argon-2d	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
AES/Rijndael (256-bit key, FIPS 197)	Argon-2id	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
ChaCha20 (256-bit key, RFC 7539)	AES-KDF	Iterations: 60000 + Compression: GZip
ChaCha20 (256-bit key, RFC 7539)	Argon-2d	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
ChaCha20 (256-bit key, RFC 7539)	Argon-2id	Iterations: 2 + Memory: 64 + Parallelsim: 2 + Compression: GZip
could you provide more informations about your database? do you use password and also a keyfile ?
