### ISSUE TITLE
App Store: app not available in your country

### ISSUE THREAD

**Issue by l4n-socrates** [FrankHausmann/IOSKeePass#16]
Hello,

a few weeks ago, i could install the app with no problems via the app store on my iphone.
Now, i cant find the app anymore on the app store. When i google the name, i can find the app store link, but, when i click on it, the following error pops up:
"App nicht verfügbar Diese App ist derzeit in deinem Land oder deiner Region nicht verfügbar"
-> App not available in region or country

I'm from Germany.

**Comment by FrankHausmann** [comment]
Hi,

yes that's right. 

After publishing the Version 2.0.0 to the App Store (Support for KDBX V4 formats), we detect in a special situation that the key db can be corrupted. That´s the reason for rejecting this from the Apple App Store.
A new Version 2.0.4 is waiting for review by the apple review Team.

I´m from Germany too. :-)

**Comment by l4n-socrates** [comment]
Thanks for the fast reply.
The information about my origin was only because of the error in the app store, sometimes apps are not availeblein some countries.

Okay, than i'm waiting for 2.0.4! Thanks again
Grüße aus Brandenburg :)
