### ISSUE TITLE
IOSKeePass crashes when adding/changing item

### ISSUE THREAD

**Issue by nicecolor538** [FrankHausmann/IOSKeePass#19]
I am using a KeePass-file (V 3.1) which was created with KeePass on a PC and imported via owncloud. It is working fine with IOSKeePass in terms of reading the file. I can search it, copy passwords, open URLs. However, as soon as I want to change anything in the file (adding, changing, moving), the app crashes.

iphone x with IOS 14.5.1 , IOSKeePass V 2.1.0

Any idea? Frank

**Comment by FrankHausmann** [comment]
Hi,

I suspect it is not a crash but possibly an impatient user.
Because IOSKEEPASS is not thread-safe in all areas, threads can overlap when encrypting content. The remedy is to either wait until it has been saved, which can take up to 30 seconds depending on the number of rounds, threads, repeats and memory. Please also compare the encryption settings via the tool button. Some Keepass PC versions make over 50 million rounds by default, so it can take a while on the ARM CPU, I think values from 10000 rounds are very safe.

**Comment by FrankHausmann** [comment]
Hi, is it possible that you provide me a test db,

so I can better understand this possible error.

**Comment by FrankHausmann** [comment]
There is an error in connection with the
ChaCha20 and AES encryption method when attaching Jpeg images to entries as a file.

The problem lies in an unsafe type pointer from the NSData class.

Please use a different encryption method when attaching jpg's to entries.

**Comment by nicecolor538** [comment]
Hi,

 

I do not think that it is impatience. The app does not freeze, it closes immediately when I try to change anything (moving, adding, editing). Even adding a group causes a crash.

 

Number of rounds is set to 60,000

 

Frank

 

 

=======================================

PD Dr.med. Frank Bloos

Kaninchenweg 7

07749 Jena

 

 

Von: Frank Hausmann ***@***.***>
Antworten an: FrankHausmann/IOSKeePass ***@***.***>
Datum: Montag, 7. Juni 2021 um 16:24
An: FrankHausmann/IOSKeePass ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Betreff: Re: [FrankHausmann/IOSKeePass] IOSKeePass crashes when adding/changing item (#19)

 

Hi,

I suspect it is not a crash but possibly an impatient user.
Because IOSKEEPASS is not thread-safe in all areas, threads can overlap when encrypting content. The remedy is to either wait until it has been saved, which can take up to 30 seconds depending on the number of rounds, threads, repeats and memory. Please also compare the encryption settings via the tool button. Some Keepass PC versions make over 50 million rounds by default, so it can take a while on the ARM CPU, I think values from 10000 rounds are very safe.

**Comment by nicecolor538** [comment]
I have stripped the database down to 4 entries on my Mac (using MacPass) and filled them with dummies. The password is »test«.

 

I have uploaded this test database to my iphone. The error is still there.

 

Frank

 

 

Von: Frank Hausmann ***@***.***>
Antworten an: FrankHausmann/IOSKeePass ***@***.***>
Datum: Mittwoch, 9. Juni 2021 um 09:41
An: FrankHausmann/IOSKeePass ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Betreff: Re: [FrankHausmann/IOSKeePass] IOSKeePass crashes when adding/changing item (#19)

 

Hi, is it possible that you provide me a test db,

so I can better understand this possible error.

**Comment by FrankHausmann** [comment]
I tested with MacPass
Version 0.7 with these settings.
Everything's works fine.
![image](https://user-images.githubusercontent.com/67282017/121367536-aba5fb80-c93a-11eb-9af0-53cb4ef5c991.png)

**Comment by FrankHausmann** [comment]
After a long term Testing, with all iPhones in Simulator and all different Encrypt/Decrypt parameters in MacPass I can't find any issue nearly your situation. For me and all the other users that maybe have the same issue like yours it is very nice if you can provide your Test DB. Please share your Test DB via email add fhausmann at unicomedv dot de

Thanks a lot

**Comment by nicecolor538** [comment]
Ok, thanks for looking into this issue. I really wonder why this happens on my iphone.

 

Frank

 

Von: Frank Hausmann ***@***.***>
Antworten an: FrankHausmann/IOSKeePass ***@***.***>
Datum: Mittwoch, 9. Juni 2021 um 20:33
An: FrankHausmann/IOSKeePass ***@***.***>
Cc: ***@***.***" ***@***.***>, Author ***@***.***>
Betreff: Re: [FrankHausmann/IOSKeePass] IOSKeePass crashes when adding/changing item (#19)

 

After a long term Testing, with all iPhones in Simulator and all different Encrypt/Decrypt parameters in MacPass I can't find any issue nearly your situation. For me and all the other users that maybe have the same issue like yours it is very nice if you can provide your Test DB. Please share your Test DB via email add fhausmann at unicomedv dot de

Thanks a lot
