### ISSUE TITLE
App shutdown by clicking on an entree

### ISSUE THREAD

**Issue by Hyp3rion** [FrankHausmann/IOSKeePass#2]
Hello ,

Just noticed that since update of one time password, the app shutdown when we select an entree. 
I tested with or without FaceTime, same issue.

The problem occurs after choosing an entree (selecting DB and/or group is ok), the app shutdown.

Problem was noticed on different devices (different IPhones ).

Rebooting iPhone doesn’t solve it.
Any idea how I can solve it ? 

Does someone meet the same problem?

Thank you in advance for your support.

Hyp3rion

**Comment by FrankHausmann** [comment]
Hi,

on all simulators and phones like 10,11 i don't see this issue.

Ask:
Which IOS versions were used?
Which iPhone versions were used?

is it possible to send or provide me a test kdb that was created under IOSKeepass, where such an entry is available.

When I have such a file I will run a debug session with the simulator of your Iphone version to see why this happens.

Please keep in mind that it can take a while as it is a non-profit project.

best regards

**Comment by Hyp3rion** [comment]
Hi,

Thanks for the prompt reply.

IOS: 13.5.1
IPhone: XR

IOS: 13.6.1
iPhone : 7 Plus

Both same problem, I’m in Madagascar with my XR and my wife in France with the 7 Plus. :)

I don’t know how to send the test DB...

😞

Hyp3rion

**Comment by Hyp3rion** [comment]
Hi,

Thanks for the prompt reply.

IOS: 13.5.1
IPhone: XR

IOS: 13.6.1
iPhone : 7 Plus

Both same problem, I’m in Madagascar with my XR and my wife in France with the 7 Plus. :)

**Comment by FrankHausmann** [comment]
Hi,
An exception is triggered in the app, which is related to KDB's version 1.x and the further development of one-time passwords. OTP feature requires dynamic custom fields which version 2.x of the KDB offers, and 1.x does not.

A fix to catch the exception will be available in the next version 1.8.1 via the App Store.

**Comment by Hyp3rion** [comment]
Thanks !
