### ISSUE TITLE
Error Message 

### ISSUE THREAD

**Issue by Caddode** [FrankHausmann/IOSKeePass#25]
![89F7B02E-A32B-4F3B-ACA2-6AE5FB748B4F](https://user-images.githubusercontent.com/32367200/147960608-6617e3aa-f3c2-4de4-a322-0b01af1e06ac.jpeg)
I don‘t need this Message.

**Comment by FrankHausmann** [comment]
then switch it off in Settings->Enable Cloud Backup
By default it is not switch on !!!

**Comment by Caddode** [comment]
This message comes all the time. Doesn‘t matter how the switch is used.

**Comment by FrankHausmann** [comment]
Ok this is a warning only, but only visible if it is disabled Sorry
I fixed this and an update is one the way Sorry
