### ISSUE TITLE
Notification about sync even if it's disabled

### ISSUE THREAD

**Issue by El-Marti** [FrankHausmann/IOSKeePass#26]
Hi,

Each time I am opening a database, I have a notification at the top even if I have disabled the sync/backup setting.
Could you please fix this ?

Regards,

Eloi

![keepass](https://user-images.githubusercontent.com/82654494/148037506-efa8b5bc-82c3-45a3-bdea-ef81554e76cb.png)

**Comment by FrankHausmann** [comment]
Hi, 

Yes i know it, and i have Fixed yesterday and upload to App Store, the update is in review by Apple and on the way
