### ISSUE TITLE
Error: AADSTS50020 occurs when try to login to OneDrive

### ISSUE THREAD

**Issue by terence4444** [FrankHausmann/IOSKeePass#35]
Thanks a lot for adding OneDrive support.
But when I tried OneDrive login, error [AADSTS50020 ](https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-not-exist) occurred.

This is a personal Microsoft 365 account with @msn.com domain.
Please let me know if anything else needs to be provided.

> AADSTS50020: User account '(deleted)@msn.com' from identity provider 'live.com' does not exist in tenant 'UniCom EDV Service & Entwicklung GmbH' and cannot access the application '137e1fe9-5666-4eb1-9a36-168fa28d4dea'(IOSKEEPASS) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

> Request Id: 102de925-9abe-4f8c-817e-5652b6882100
Correlation Id: 063a8a29-48bd-4ea6-924e-4d80c17639ad
Timestamp: 2022-06-25T16:00:52Z
Message: AADSTS50020: User account '(deleted)@msn.com' from identity provider 'live.com' does not exist in tenant 'UniCom EDV Service & Entwicklung GmbH' and cannot access the application '137e1fe9-5666-4eb1-9a36-168fa28d4dea'(IOSKEEPASS) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

Best regards

**Comment by FrankHausmann** [comment]
Many thanks for the detailed error description, as in the Microsoft documentation https://docs.microsoft.com/en-us/troubleshoot/azure/active-directory/error-code-aadsts50020-user-account-identity-provider-does-  not-exist, personal accounts are not supported for case 1 security reasons.  sorry for that

**Comment by terence4444** [comment]
Thank you for the quick response!
