### ISSUE TITLE
File does not save over original file

### ISSUE THREAD

**Issue by napalmcsr** [FrankHausmann/IOSKeePass#36]
I share a db with my wife and we sync using icloud. If I use ioskeepass it saves to its own directory instead of where the file came from.
Thanks.

**Comment by FrankHausmann** [comment]
Yes right, IOSKeePass basically stores its files in the secure sandbox of the IOSKeePass APP itself, when IOS sharing a KeePass file this is always a one way street from the IOSKeePass app, so from sharepoint to the sandbox.

But, there is the possibility via the setting "Cloud Backup" at "Apple, Microsoft or own cloud" to synchronize the Keepass file automatically with the corresponding cloud provider when leaving. 

Also, it is then indicated that a newer file on the respective cloud, but to synchronize this manually, just swipe left in the file overview and select sync.

Everything works wonderfully if the access data in the "Cloud Backup" area on both Iphones have been set correctly.

Cheers
