### ISSUE TITLE
OneDrive Instructions

### ISSUE THREAD

**Issue by jdlee77** [FrankHausmann/IOSKeePass#37]
Hello, 

I am having trouble accessing my .kdbx located on OneDrive from the IOSKeePass app. Any instructions detailing this would be greatly appreciated.

**Comment by FrankHausmann** [comment]
Hi,

Basically IOSKeePass works with its KDBX files Local.

1) If you want to get a KDBX only from the cloud, use the Import button in the list of your KDBX files, accessible below next to the question mark.

2) If you want to synchronize with OneDrive, in Settings select Cloud Backup, OneDrive and your access data to Office365.

Note: IOSKeePass do only supports school and business accounts for OneDrive.
