### ISSUE TITLE
Consider changing the "MinimumOSVersion" to something more realistic?

### ISSUE THREAD

**Issue by SwiftMove** [FrankHausmann/IOSKeePass#4]
I was hoping to migrate from MiniKeePass to iOSKeePass, but the only version (v1.8.1) that is compatible with the current iOS version that I'm on (13.5.1) doesn't work. It has the issue where it won't open any of the databases. It appears that you've resolved this issue in v1.8.2, but for some odd reason you've chosen to raise the "MinimumOSVersion" to "13.7". Perhaps maybe this was an oversight? I'm not even sure why you'd raise it that high as you're preventing this app from being installed on a lot of older devices that cannot update to iOS 13. It would make more sense to at least change it to iOS 12, or iOS 13 at the very least. 

I hope you'll consider.

**Comment by FrankHausmann** [comment]
Sure, this fork is a migration from Minkeepass, but not without revising the code where possible and connecting it to the latest Apple technology, Apple itself does not offer any support for new technologies for devices that are older than 5 years. I recommend taking the original Minikeepass code and maintaining your own fork for iOS systems that are older than 5 years, in any case I will only provide support and further development on current systems just like Apple itself.
I'm sorry I haven't got a more useful answer for you.

ps. IOSKeePass runs on Apple devices from 2015 until today.
