### ISSUE TITLE
Open notes without being in editing mode

### ISSUE THREAD

**Issue by El-Marti** [FrankHausmann/IOSKeePass#45]
I use a lot the « notes » section in the keep as app for many entries.
For example, under my bank account, I keep my credit card number, my account number, etc…. 

And sometimes, I just want to copy paste a part of this information into another app.
But when I open an entry and click on the notes sectionto copy paste some text, that does not stop me from editing ! So by selecting text I can easily make a mistake like deleting or adding a letter…..

Could you please add an explicit edit button to make text selection more secure.

**Comment by FrankHausmann** [comment]
Do not touch the Button in the Toolbar, instead Please swipe the text editor to the bottom this will close the Texteditor and nothing will happens with your Entry

**Comment by El-Marti** [comment]
Hi, it works but it can be very confusing when you make a mistake (delete a part of the note accidentally…).
