### ISSUE TITLE
IOSKeePass Spanish Version

### ISSUE THREAD

**Issue by F3d0s** [FrankHausmann/IOSKeePass#46]
In the iOS App Store, I've seen an user requesting to release a Spanish version of this good app. The dev invited him to open a discussion here but I see he haven't done that.

I am good with the English version buy if needed, I can help with the translation.

**Comment by FrankHausmann** [comment]
Hello Yes gladly, I had about 1 year ago rudimentary the most important also translated to spanish with the deepl translator from english to german.

It would be good if someone with the home language could proofread, do the following.

in Github area code download the original en.lproj and es.lproj files, and correct the file es.lproj.
On the left is always the origianl english text and on the right the translation, then upload the file again or send it to me.

When IOSKeePass is started, the language of the Apple device is automatically detected, at least normally.
If no language detect it falls back to english

Just try it by changing the language in the Iphone and restarting IOSKeePass.
