### ISSUE TITLE
Rename Database not possible

### ISSUE THREAD

**Issue by Caddode** [FrankHausmann/IOSKeePass#47]
A long touch in the overview will not help
![long-touch](https://user-images.githubusercontent.com/32367200/215444214-e7629321-62c5-4fd0-84a2-fbd680bbfcca.jpg)

**Comment by FrankHausmann** [comment]
Change Masterkey, do also a rename of the keePass File

**Comment by Caddode** [comment]
Unfortunately, this does not work as easily as before the update. Either I am too stupid or it is too complicated. I get in the 1st attempt the message:
![2023-01-31 15 53 17](https://user-images.githubusercontent.com/32367200/215795654-24d44ba5-349d-4d05-ab7a-e0ae0ba97599.PNG)
If it then still works, after I enter the password 3x I do not get the new name, but this:
![2023-01-31 16 00 17](https://user-images.githubusercontent.com/32367200/215796371-0ccf6117-dd27-439f-882c-b0120feaad5b.jpg)
