### ISSUE TITLE
kdbx file is deleted when double tapping on it

### ISSUE THREAD

**Issue by Nbolis67** [FrankHausmann/IOSKeePass#51]
I can reproduce the following problem: the kdbx file is stored locally on my iPhone SE 2nd gen (iOS 16.3.1). If I now double-tap the kdbx file under Files in the IOSKeePass folder, it is deleted without any warning. The behaviour is independent of the database version. Maybe it is a feature but whit my nervous fingers this would make the tool worthless for me.

**Comment by FrankHausmann** [comment]
Then it is indeed better you leave IOSKeePass alone, and use a solution for nervous fingers.

The problem, with IOSKeePass the file extension .kdbx and .keyx is registered, which means if you try to create a select in the local folder of the iphones a new DB, and the old one is overwritten, this is blocked ioskeepass crashes and the data is lost. When I have time again, I will offer a solution for nervous fingers, but may take time. For this reason I have mentioned 2000 times you want to use the import button in the bottom center right of the file viewer of IOSKeepass to bring a KeePass DB cleanly in localen Folder App, the same applies to KeyFiles.
