### ISSUE TITLE
Close db on time out not working 

### ISSUE THREAD

**Issue by pspiske** [FrankHausmann/IOSKeePass#7]
Using iPhone 6S, iOS 14.2 iosKeepass 1.8.5
Database does not lock after settings are on any setting immediately, 30 sec, 1 min, 2 min, or 5 min.
Using fingerprint unlock. Requires hard close of keepass after each use.

**Comment by Panache1** [comment]
On my phone you don’t have to close IOS KeePass, but you do have to go back to the Files screen for it to lock.
