### ISSUE TITLE
Can't load .kdbx from installed OneDrive app

### ISSUE THREAD

**Issue by clorteau** [FrankHausmann/IOSKeePass#9]
Hello,

This looks pretty good and thanks for implementing an opensource keepass client. When I tap the open button and navigate to OneDrive then select my .kdbx file the app simply goes back to the list of databases that remains empty.

**Comment by FrankHausmann** [comment]
Yes, sure that can be, for better understanding. 

IOSKeePass need a local Folder on your Iphone, unfortunely this folder don´t create automatically.
Please create a new Local Keepass db by touch on the '+' button, After you create the first local DB, a Local folder named IOSKeePass is created, and you can import from any remote folders as expected.
